id: P76455717
initial_creation_type: input
source_metadata:
  title: Chögyal Pakpa Lodrö Gyaltsen
  language: fr
  description: 'Texts by and about the great Sakya master Chögyal Pakpa Lodrö Gyaltsen
    (chos rgyal ’phags pa blo gros rgyal mtshan, 1235–1280):'
  volume:
    bca174e85e614b55851eba96e6a63c17:
      title: Dhāraṇī of Goddess Parṇaśavarī
      parent: Dhāraṇī
    e0c4f6e1d2f445c1b55d47d8ac9896c2:
      title: Short Maṇḍala Offering
      parent: Offering
    1343b5a23bf743a89c07ec2eb4c283fe:
      title: Thirty-Seven Point Maṇḍala Offering
      parent: Offering
    8c0f790279034b01ad10f9798fbe11b8:
      title: Töpa Gyatsoma Offering Prayer
      parent: Offering
    052a29deee234ed18df03218e0cbaf8c:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Sādhanas
created_at: '2022-02-28T22:43:55.173476'
last_modified_at: '2022-02-28T22:43:55.173479'
